name: Update options documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update docs/options.md
        run: nix build .#docs && cat ./result > docs/options.md

      - name: Commit the changed files
        uses: EndBug/add-and-commit@v9
        with:
          add: ./docs/options.md
          default_author: github_actions
          message: 'Update options.md'
